### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by david4worx** [Enrise/RESTWorkbench#49]
Unit tests are missing and need to be intergrated.
### First to test are:
- OAuth signing with requests that are PUT/POST
- Custom HTTP build query method
- Reading annotations and building data structure
### Possible problems:
- Per project different version of unit tests
- Different versions of Glitch
- Different versions of Zend (v1, v2)
- ...

**Comment by eXistenZNL** [comment]
This repository has been unmaintained for years, closing this issue.
